/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mery.votingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author merye
 */
public class AdminHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminHomePanel
     */
    public AdminHomePanel() {
        initComponents();

        ImageIcon icon2 = new ImageIcon("C:\\Users\\merye\\Downloads\\REPUBLIC OF TÜRKİYE.png");
        Image img2 = icon2.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        icon2.setImage(img2);
        jLabel1.setIcon(icon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new com.mery.votingsystem.GradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createCandidatejButton = new javax.swing.JButton();
        UserjButton = new javax.swing.JButton();
        logoutjButton = new javax.swing.JButton();
        gradientPanel2 = new com.mery.votingsystem.GradientPanel();
        startjButton = new javax.swing.JButton();
        electionjButton1 = new javax.swing.JButton();
        presidentialjCheckBox = new javax.swing.JCheckBox();
        mukhtarjCheckBox = new javax.swing.JCheckBox();
        municipaljCheckBox = new javax.swing.JCheckBox();
        presidentialStatusjLabel = new javax.swing.JLabel();
        mukhtarStatusjLabel = new javax.swing.JLabel();
        municipalStatusjLabel = new javax.swing.JLabel();
        removeCandidatejButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 226, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setGradientEndd(new java.awt.Color(214, 230, 242));
        gradientPanel1.setGradientStart(new java.awt.Color(118, 159, 205));
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 45, 78));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Home Page");
        gradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 220, 60));

        jLabel1.setText("jLabel1");
        gradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 200, 200));

        createCandidatejButton.setBackground(new java.awt.Color(17, 45, 78));
        createCandidatejButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        createCandidatejButton.setText("Create Candidate");
        createCandidatejButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createCandidatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCandidatejButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(createCandidatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 220, 40));

        UserjButton.setBackground(new java.awt.Color(17, 45, 78));
        UserjButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        UserjButton.setText("Create User");
        UserjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(UserjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 220, 40));

        logoutjButton.setBackground(new java.awt.Color(17, 45, 78));
        logoutjButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        logoutjButton.setText("Log Out");
        logoutjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(logoutjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 40));

        gradientPanel2.setGradientEndd(new java.awt.Color(17, 45, 78));
        gradientPanel2.setGradientStart(new java.awt.Color(17, 45, 78));

        javax.swing.GroupLayout gradientPanel2Layout = new javax.swing.GroupLayout(gradientPanel2);
        gradientPanel2.setLayout(gradientPanel2Layout);
        gradientPanel2Layout.setHorizontalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gradientPanel2Layout.setVerticalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gradientPanel1.add(gradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 765, 5));

        startjButton.setBackground(new java.awt.Color(17, 45, 78));
        startjButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        startjButton.setText("Change Election Status");
        startjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(startjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 270, 40));

        electionjButton1.setBackground(new java.awt.Color(17, 45, 78));
        electionjButton1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        electionjButton1.setText("Create Election");
        electionjButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        electionjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electionjButton1ActionPerformed(evt);
            }
        });
        gradientPanel1.add(electionjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 270, 40));

        presidentialjCheckBox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        presidentialjCheckBox.setForeground(new java.awt.Color(17, 45, 78));
        presidentialjCheckBox.setText("Presidential");
        presidentialjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentialjCheckBoxActionPerformed(evt);
            }
        });
        gradientPanel1.add(presidentialjCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        mukhtarjCheckBox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        mukhtarjCheckBox.setForeground(new java.awt.Color(17, 45, 78));
        mukhtarjCheckBox.setText("Mukhtar");
        mukhtarjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mukhtarjCheckBoxActionPerformed(evt);
            }
        });
        gradientPanel1.add(mukhtarjCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        municipaljCheckBox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        municipaljCheckBox.setForeground(new java.awt.Color(17, 45, 78));
        municipaljCheckBox.setText("Municipal");
        municipaljCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipaljCheckBoxActionPerformed(evt);
            }
        });
        gradientPanel1.add(municipaljCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        presidentialStatusjLabel.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        presidentialStatusjLabel.setForeground(new java.awt.Color(17, 45, 78));
        presidentialStatusjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        presidentialStatusjLabel.setText("*not started");
        gradientPanel1.add(presidentialStatusjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 90, 20));

        mukhtarStatusjLabel.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        mukhtarStatusjLabel.setForeground(new java.awt.Color(17, 45, 78));
        mukhtarStatusjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mukhtarStatusjLabel.setText("*not started");
        gradientPanel1.add(mukhtarStatusjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 70, 20));

        municipalStatusjLabel.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        municipalStatusjLabel.setForeground(new java.awt.Color(17, 45, 78));
        municipalStatusjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        municipalStatusjLabel.setText("*not started");
        gradientPanel1.add(municipalStatusjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 80, 20));

        removeCandidatejButton.setBackground(new java.awt.Color(17, 45, 78));
        removeCandidatejButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        removeCandidatejButton.setText("Remove Candidate");
        removeCandidatejButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeCandidatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCandidatejButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(removeCandidatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 220, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 45, 78));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("*Select the election to start - finish.");
        gradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 270, 20));

        add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void UserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserjButtonActionPerformed
        MainFrame.setPage("createUserPanel");
    }//GEN-LAST:event_UserjButtonActionPerformed

    private void createCandidatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCandidatejButtonActionPerformed
        MainFrame.setPage("createCandidatePanel");
    }//GEN-LAST:event_createCandidatejButtonActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        MainFrame.setPage("loginPanel");
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void startjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startjButtonActionPerformed
        if (mukhtarjCheckBox.isSelected()) {
            MainFrame.setMukhtarElectionStarted(true);
            mukhtarStatusjLabel.setText("started");
        } else {
            MainFrame.setMukhtarElectionStarted(false);
            mukhtarStatusjLabel.setText("finished");
        }

        if (municipaljCheckBox.isSelected()) {
            MainFrame.setMunicipalElectionStarted(true);
            municipalStatusjLabel.setText("started");
        } else {
            MainFrame.setMunicipalElectionStarted(false);
            municipalStatusjLabel.setText("finished");
        }

        if (presidentialjCheckBox.isSelected()) {
            MainFrame.setPresidentialElectionStarted(true);
            presidentialStatusjLabel.setText("started");
        } else {
            MainFrame.setPresidentialElectionStarted(false);
            presidentialStatusjLabel.setText("finished");
        }
    }//GEN-LAST:event_startjButtonActionPerformed

    private void electionjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electionjButton1ActionPerformed
        MainFrame.setPage("createElectionPanel");
    }//GEN-LAST:event_electionjButton1ActionPerformed

    private void presidentialjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentialjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presidentialjCheckBoxActionPerformed

    private void mukhtarjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mukhtarjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mukhtarjCheckBoxActionPerformed

    private void municipaljCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipaljCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipaljCheckBoxActionPerformed

    private void removeCandidatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCandidatejButtonActionPerformed
        if (MainFrame.isMukhtarElectionStarted() || MainFrame.isMunicipalElectionStarted() || MainFrame.isPresidentialElectionStarted()) {
            JOptionPane.showMessageDialog(this, "Elections started, you can not remove any candidate.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else {
            MainFrame.setPage("removeCandidatePanel");
        }
    }//GEN-LAST:event_removeCandidatejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserjButton;
    private javax.swing.JButton createCandidatejButton;
    private javax.swing.JButton electionjButton1;
    private com.mery.votingsystem.GradientPanel gradientPanel1;
    private com.mery.votingsystem.GradientPanel gradientPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JLabel mukhtarStatusjLabel;
    private javax.swing.JCheckBox mukhtarjCheckBox;
    private javax.swing.JLabel municipalStatusjLabel;
    private javax.swing.JCheckBox municipaljCheckBox;
    private javax.swing.JLabel presidentialStatusjLabel;
    private javax.swing.JCheckBox presidentialjCheckBox;
    private javax.swing.JButton removeCandidatejButton;
    private javax.swing.JButton startjButton;
    // End of variables declaration//GEN-END:variables
}
