/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mery.votingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author merye
 */
public class AdminHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminHomePanel
     */
    public AdminHomePanel() {
        initComponents();

        ImageIcon icon2 = new ImageIcon("C:\\Users\\merye\\Downloads\\REPUBLIC OF TÜRKİYE.png");
        Image img2 = icon2.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        icon2.setImage(img2);
        jLabel1.setIcon(icon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new com.mery.votingsystem.GradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        candidatejButton = new javax.swing.JButton();
        UserjButton = new javax.swing.JButton();
        logoutjButton = new javax.swing.JButton();
        gradientPanel2 = new com.mery.votingsystem.GradientPanel();
        startjButton = new javax.swing.JButton();
        electionjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(219, 226, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setGradientEndd(new java.awt.Color(214, 230, 242));
        gradientPanel1.setGradientStart(new java.awt.Color(118, 159, 205));
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 45, 78));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Home Page");
        gradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 220, 60));

        jLabel1.setText("jLabel1");
        gradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 200, 200));

        candidatejButton.setBackground(new java.awt.Color(17, 45, 78));
        candidatejButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        candidatejButton.setText("Create Candidate");
        candidatejButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        candidatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatejButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(candidatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 220, 50));

        UserjButton.setBackground(new java.awt.Color(17, 45, 78));
        UserjButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        UserjButton.setText("Create User");
        UserjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(UserjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 170, 50));

        logoutjButton.setBackground(new java.awt.Color(17, 45, 78));
        logoutjButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        logoutjButton.setText("Log Out");
        logoutjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(logoutjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 40));

        gradientPanel2.setGradientEndd(new java.awt.Color(17, 45, 78));
        gradientPanel2.setGradientStart(new java.awt.Color(17, 45, 78));

        javax.swing.GroupLayout gradientPanel2Layout = new javax.swing.GroupLayout(gradientPanel2);
        gradientPanel2.setLayout(gradientPanel2Layout);
        gradientPanel2Layout.setHorizontalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        gradientPanel2Layout.setVerticalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gradientPanel1.add(gradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 765, 5));

        startjButton.setBackground(new java.awt.Color(17, 45, 78));
        startjButton.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        startjButton.setText("Start Elections");
        startjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(startjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 220, 50));

        electionjButton1.setBackground(new java.awt.Color(17, 45, 78));
        electionjButton1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        electionjButton1.setText("Create Election");
        electionjButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        electionjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electionjButton1ActionPerformed(evt);
            }
        });
        gradientPanel1.add(electionjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 220, 50));

        add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void UserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserjButtonActionPerformed
        MainFrame.setPage("createUserPanel");
    }//GEN-LAST:event_UserjButtonActionPerformed

    private void candidatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatejButtonActionPerformed
        MainFrame.setPage("createCandidatePanel");
    }//GEN-LAST:event_candidatejButtonActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        MainFrame.setPage("loginPanel");
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void startjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startjButtonActionPerformed
        MainFrame.setElectionStatus(!MainFrame.getElectionStatus());
        if (MainFrame.getElectionStatus()) {
            startjButton.setText("Finish Elections");
        } else {
            startjButton.setText("Start Elections");
        }

    }//GEN-LAST:event_startjButtonActionPerformed

    private void electionjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electionjButton1ActionPerformed
        MainFrame.setPage("createElectionPanel");
    }//GEN-LAST:event_electionjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserjButton;
    private javax.swing.JButton candidatejButton;
    private javax.swing.JButton electionjButton1;
    private com.mery.votingsystem.GradientPanel gradientPanel1;
    private com.mery.votingsystem.GradientPanel gradientPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JButton startjButton;
    // End of variables declaration//GEN-END:variables
}
