/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mery.votingsystem;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author merye
 */
public class CreateCandidatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCandidatePanel
     */
    public CreateCandidatePanel() {
        initComponents();
        refreshCity();
        refreshNeigh();
    }

    public void refreshCity() {
        jComboBoxCity.removeAllItems();
        for (City city : MSK.cities) {
            jComboBoxCity.addItem(city);
        }
        jComboBoxCity.setSelectedIndex(0);
    }

    public void refreshNeigh() {
        jComboBoxNeigh.removeAllItems();
        City selectedCity = (City) jComboBoxCity.getSelectedItem();
        for (String neigh : selectedCity.neighbourhoods) {
            jComboBoxNeigh.addItem(neigh);
        }
        jComboBoxNeigh.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new com.mery.votingsystem.GradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxNeigh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCity = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jButtonAddPicture = new javax.swing.JButton();
        jLabelIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 247, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setBackground(new java.awt.Color(17, 45, 78));
        gradientPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gradientPanel1.setForeground(new java.awt.Color(17, 45, 78));
        gradientPanel1.setGradientEndd(new java.awt.Color(214, 230, 242));
        gradientPanel1.setGradientStart(new java.awt.Color(118, 159, 205));
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 45, 78));
        jLabel1.setText("Neighbourhood:");
        gradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 45, 78));
        jLabel4.setText("Candidate's Portrait:");
        gradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 190, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 45, 78));
        jLabel5.setText("Surname:");
        gradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, -1));

        jComboBoxNeigh.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        gradientPanel1.add(jComboBoxNeigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 45, 78));
        jLabel6.setText("Age:");
        gradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 45, 78));
        jLabel2.setText("*Please select the neighbourhood in which the individual is nominated.");
        gradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 400, 20));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(17, 45, 78));
        jLabel8.setText("City:");
        gradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, -1));

        jComboBoxCity.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCityActionPerformed(evt);
            }
        });
        gradientPanel1.add(jComboBoxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 180, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(17, 45, 78));
        jLabel9.setText("Name:");
        gradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(17, 45, 78));
        jLabel10.setText("*Please select the city in which the individual is nominated.");
        gradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 320, 20));

        jTextFieldAge.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });
        gradientPanel1.add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 180, -1));

        jTextFieldName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        gradientPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, -1));

        jTextFieldSurname.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        gradientPanel1.add(jTextFieldSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, -1));

        savejButton.setBackground(new java.awt.Color(17, 45, 78));
        savejButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        savejButton.setText("Save");
        savejButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(savejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 80, 30));

        backjButton.setBackground(new java.awt.Color(17, 45, 78));
        backjButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        backjButton.setText("Back");
        backjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 80, 30));

        jButtonAddPicture.setBackground(new java.awt.Color(17, 45, 78));
        jButtonAddPicture.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonAddPicture.setText("Add Picture");
        jButtonAddPicture.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPictureActionPerformed(evt);
            }
        });
        gradientPanel1.add(jButtonAddPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 100, 30));
        gradientPanel1.add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 170, 140));

        add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, 400));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 45, 78));
        jLabel3.setText("Create Candidate");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(17, 45, 78));
        jLabel7.setText("Please fill in the information completely.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        if (jTextFieldName.getText().isEmpty() || jTextFieldSurname.getText().isEmpty() || jTextFieldAge.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill the empty areas!", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int age;
        try {

            age = Integer.parseInt(jTextFieldAge.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Wrong Information!", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String firstname = jTextFieldName.getText();
        String surname = jTextFieldSurname.getText();
        City city = (City) jComboBoxCity.getSelectedItem();
        String neigh = jComboBoxNeigh.getSelectedItem().toString();
        Candidate candidate = new Candidate(age, city, neigh, surname, firstname, surname, neigh);
        MSK.people.add(candidate);

        JOptionPane.showMessageDialog(this, "The record has been created!", "Successful", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_savejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        MainFrame.setPage("adminPanel");
    }//GEN-LAST:event_backjButtonActionPerformed

    private void jComboBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCityActionPerformed
        refreshNeigh();
    }//GEN-LAST:event_jComboBoxCityActionPerformed

    private void jButtonAddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPictureActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("4 Extension Suported", "jpg","png","jpeg","svg");
        fileChooser.setFileFilter(filter);
        int selected= fileChooser.showOpenDialog(this);
        
        if(selected==JFileChooser.APPROVE_OPTION){
            File fle= fileChooser.getSelectedFile();
            String getSelectedImage=fle.getAbsolutePath();
            JOptionPane.showMessageDialog(null, getSelectedImage);
            ImageIcon imageIcon = new ImageIcon(getSelectedImage);
            jLabelIcon.setIcon(imageIcon);
            
            Image imFit = imageIcon.getImage();
            Image imgFit= imFit.getScaledInstance(jLabelIcon.getWidth(), jLabelIcon.getHeight(), Image.SCALE_SMOOTH);
        }
        
    }//GEN-LAST:event_jButtonAddPictureActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private com.mery.votingsystem.GradientPanel gradientPanel1;
    private javax.swing.JButton jButtonAddPicture;
    private javax.swing.JComboBox<Object> jComboBoxCity;
    private javax.swing.JComboBox<Object> jComboBoxNeigh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JButton savejButton;
    // End of variables declaration//GEN-END:variables
}
