/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mery.votingsystem;

import com.mery.votingsystem.coreclasses.Candidate;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author merye
 */
public class CVFrame extends javax.swing.JFrame {

    /**
     * Creates new form CVFrame
     *
     * @param candidate
     * @param electionType
     */
    public CVFrame(Candidate candidate, String electionType) {
        initComponents();
        nameSurnamejLabel.setText(candidate.getFirstName() + " " + candidate.getSurname());
        cityjLabel.setText(candidate.city.toString());
        agejLabel.setText(candidate.age + " ");
        neighjLabel.setText(candidate.neighbourhood);
        ElectionTypejLabel.setText(electionType);
            ImageIcon icon2 = new ImageIcon("C:\\Users\\merye\\Downloads\\Daco_416356.png");
            Image img2 = icon2.getImage().getScaledInstance(150, 200, Image.SCALE_SMOOTH);
            icon2.setImage(img2);
            jLabel6.setIcon(icon2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new com.mery.votingsystem.GradientPanel();
        nameSurnamejLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        candidacyjLabel = new javax.swing.JLabel();
        agejLabel = new javax.swing.JLabel();
        neighjLabel = new javax.swing.JLabel();
        ElectionTypejLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cityjLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gradientPanel2 = new com.mery.votingsystem.GradientPanel();
        gradientPanel3 = new com.mery.votingsystem.GradientPanel();

        setBackground(new java.awt.Color(17, 45, 78));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setGradientEndd(new java.awt.Color(17, 45, 78));
        gradientPanel1.setGradientStart(new java.awt.Color(17, 45, 78));
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameSurnamejLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        nameSurnamejLabel.setForeground(new java.awt.Color(249, 247, 247));
        nameSurnamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameSurnamejLabel.setText("Name Surname:");
        gradientPanel1.add(nameSurnamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 247, 247));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Neighbourhood:");
        gradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 40));

        candidacyjLabel.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        candidacyjLabel.setForeground(new java.awt.Color(249, 247, 247));
        candidacyjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        candidacyjLabel.setText("Candidacy:");
        gradientPanel1.add(candidacyjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        agejLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        agejLabel.setForeground(new java.awt.Color(249, 247, 247));
        agejLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        agejLabel.setText("Age:");
        gradientPanel1.add(agejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 190, 20));

        neighjLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        neighjLabel.setForeground(new java.awt.Color(249, 247, 247));
        neighjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        neighjLabel.setText("...");
        gradientPanel1.add(neighjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 170, 30));

        ElectionTypejLabel.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        ElectionTypejLabel.setForeground(new java.awt.Color(249, 247, 247));
        ElectionTypejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ElectionTypejLabel.setText("Election Type");
        gradientPanel1.add(ElectionTypejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 40));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 247, 247));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("City:");
        gradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 99, 30));

        cityjLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        cityjLabel.setForeground(new java.awt.Color(249, 247, 247));
        cityjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cityjLabel.setText("...");
        gradientPanel1.add(cityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 160, 30));
        gradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 200));

        getContentPane().add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 390));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 45, 78));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CV");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 99, 40));

        gradientPanel2.setGradientEndd(new java.awt.Color(219, 226, 239));
        gradientPanel2.setGradientStart(new java.awt.Color(63, 114, 175));

        gradientPanel3.setGradientEndd(new java.awt.Color(17, 45, 78));
        gradientPanel3.setGradientStart(new java.awt.Color(219, 226, 239));
        gradientPanel3.setPreferredSize(new java.awt.Dimension(249, 5));

        javax.swing.GroupLayout gradientPanel3Layout = new javax.swing.GroupLayout(gradientPanel3);
        gradientPanel3.setLayout(gradientPanel3Layout);
        gradientPanel3Layout.setHorizontalGroup(
            gradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );
        gradientPanel3Layout.setVerticalGroup(
            gradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gradientPanel2Layout = new javax.swing.GroupLayout(gradientPanel2);
        gradientPanel2.setLayout(gradientPanel2Layout);
        gradientPanel2Layout.setHorizontalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(gradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        gradientPanel2Layout.setVerticalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(gradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        getContentPane().add(gradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CVFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElectionTypejLabel;
    private javax.swing.JLabel agejLabel;
    private javax.swing.JLabel candidacyjLabel;
    private javax.swing.JLabel cityjLabel;
    private com.mery.votingsystem.GradientPanel gradientPanel1;
    private com.mery.votingsystem.GradientPanel gradientPanel2;
    private com.mery.votingsystem.GradientPanel gradientPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nameSurnamejLabel;
    private javax.swing.JLabel neighjLabel;
    // End of variables declaration//GEN-END:variables
}
